# Generated by Django 4.2.5 on 2023-10-17 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='related_exercise',
        ),
        migrations.RemoveField(
            model_name='user',
            name='related_workout_plan',
        ),
    ]
