# Generated by Django 4.2.5 on 2023-10-17 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_remove_user_related_exercise_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Set',
            new_name='TrainingSet',
        ),
    ]
