# Generated by Django 4.2.5 on 2023-10-18 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_alter_workoutplan_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='related_user',
            new_name='added_by_user',
        ),
        migrations.RenameField(
            model_name='workoutplan',
            old_name='related_user',
            new_name='added_by',
        ),
        migrations.RenameField(
            model_name='workoutplan',
            old_name='related_exercise_in_workout_plan',
            new_name='exercise_in_workout_plan',
        ),
    ]
