# Generated by Django 4.2.5 on 2023-10-18 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_rename_related_user_exercise_added_by_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bodyweight',
            old_name='weight_ID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='brokenset',
            old_name='broken_set_ID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='exercise_ID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='exerciseinworkout',
            old_name='exercise_in_workout_ID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='exerciseinworkoutplan',
            old_name='exercise_in_workout_plan_ID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='personalbest',
            old_name='personal_best_ID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='trainingset',
            old_name='set_ID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='workout',
            old_name='workout_ID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='workoutplan',
            old_name='workout_ID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='workoutplan',
            old_name='added_by',
            new_name='plan_user',
        ),
    ]
