# Generated by Django 4.2.5 on 2023-10-18 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_rename_related_exercise_exerciseinworkoutplan_exercise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bodyweight',
            old_name='related_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='brokenset',
            old_name='related_set',
            new_name='set',
        ),
        migrations.RenameField(
            model_name='exerciseinworkout',
            old_name='related_exercise',
            new_name='exercise',
        ),
        migrations.RenameField(
            model_name='exerciseinworkout',
            old_name='related_workout',
            new_name='workout',
        ),
        migrations.RenameField(
            model_name='personalbest',
            old_name='related_exercise',
            new_name='exercise',
        ),
        migrations.RenameField(
            model_name='personalbest',
            old_name='related_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='trainingset',
            old_name='related_exercise_in_workout',
            new_name='exercise',
        ),
        migrations.RenameField(
            model_name='workout',
            old_name='related_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='workout',
            old_name='related_workout_plan',
            new_name='workout_plan',
        ),
    ]
