# Generated by Django 4.2.5 on 2023-10-18 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_rename_related_user_bodyweight_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutplan',
            old_name='name',
            new_name='title',
        ),
    ]
