# Generated by Django 4.2.5 on 2023-11-26 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0011_rename_name_workoutplan_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutplan',
            old_name='exercises',
            new_name='exercises_in_plan',
        ),
        migrations.RemoveField(
            model_name='trainingset',
            name='is_broken_set',
        ),
        migrations.DeleteModel(
            name='BrokenSet',
        ),
    ]
